using CitasApp.Data;
using CitasApp.Models;
using Microsoft.EntityFrameworkCore;

namespace CitasApp.Services
{
    public static class DatabaseSeeder
    {
        public static void EnsureSeedData(CitasDbContext context)
        {
            context.Database.EnsureCreated();
            EnsureUsuariosTable(context);
            EnsureAgendaTable(context);
            RemoveLegacySeedData(context);

            var diego = EnsurePaciente(context, "Diego", "Ramirez", "diego@escuela.local", "9991002001");
            var carlos = EnsurePaciente(context, "Carlos", "Paciente", "carlos@escuela.local", "9991002002");
            var joshua = EnsureMedico(context, "Joshua", "Medico", "Medicina General", "MED-JOSHUA");
            var michelle = EnsureMedico(context, "Michelle", "Medico", "Medicina Interna", "MED-MICHELLE");
            context.SaveChanges();

            diego = context.Pacientes.Single(p => p.Email == "diego@escuela.local");
            carlos = context.Pacientes.Single(p => p.Email == "carlos@escuela.local");
            joshua = context.Medicos.Single(m => m.NumeroLicencia == "MED-JOSHUA");
            michelle = context.Medicos.Single(m => m.NumeroLicencia == "MED-MICHELLE");

            EnsureCita(context, diego.Id, joshua.Id, DateOnly.FromDateTime(DateTime.Today.AddDays(1)), new TimeOnly(9, 0), "Consulta de Diego con Joshua");
            EnsureCita(context, carlos.Id, michelle.Id, DateOnly.FromDateTime(DateTime.Today.AddDays(2)), new TimeOnly(10, 30), "Consulta de Carlos con Michelle");

            EnsureUsuario(context, "jorge", "Jorge123!", "Jorge Javier Pedrozo Romero", "Administrador", null, null);
            EnsureUsuario(context, "joshua", "Joshua123!", "Joshua Medico", "Medico", null, joshua.Id);
            EnsureUsuario(context, "michelle", "Michelle123!", "Michelle Medico", "Medico", null, michelle.Id);
            EnsureUsuario(context, "diego", "Diego123!", "Diego Ramirez", "Paciente", diego.Id, null);
            EnsureUsuario(context, "carlos", "Carlos123!", "Carlos Paciente", "Paciente", carlos.Id, null);

            context.SaveChanges();
            SyncAgenda(context);
        }

        private static void RemoveLegacySeedData(CitasDbContext context)
        {
            var legacyUsuarios = context.Usuarios
                .Where(u => u.NombreUsuario == "admin" || u.NombreUsuario == "medico" || u.NombreUsuario == "paciente")
                .ToList();
            context.Usuarios.RemoveRange(legacyUsuarios);

            var legacyCitas = context.Citas
                .Where(c => c.Motivo == "Consulta general")
                .ToList();
            var legacyCitaIds = legacyCitas.Select(c => c.Id).ToList();
            var legacyAgenda = context.Agenda
                .Where(a => legacyCitaIds.Contains(a.CitaId))
                .ToList();
            context.Agenda.RemoveRange(legacyAgenda);
            context.Citas.RemoveRange(legacyCitas);

            var legacyPacientes = context.Pacientes
                .Where(p => p.Email == "paciente.demo@escuela.local")
                .ToList();
            var legacyMedicos = context.Medicos
                .Where(m => m.NumeroLicencia == "MED-0001")
                .ToList();
            context.Pacientes.RemoveRange(legacyPacientes);
            context.Medicos.RemoveRange(legacyMedicos);

            context.SaveChanges();
        }

        private static void EnsureUsuariosTable(CitasDbContext context)
        {
            context.Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "Usuarios" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "NombreUsuario" character varying(80) NOT NULL,
                    "NombreCompleto" character varying(160) NOT NULL DEFAULT '',
                    "PasswordHash" text NOT NULL,
                    "Rol" character varying(30) NOT NULL,
                    "PacienteId" integer NULL,
                    "MedicoId" integer NULL,
                    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
                );
                """);

            context.Database.ExecuteSqlRaw("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Usuarios_NombreUsuario"
                ON "Usuarios" ("NombreUsuario");
                """);

            context.Database.ExecuteSqlRaw("""
                ALTER TABLE "Usuarios"
                ADD COLUMN IF NOT EXISTS "NombreCompleto" character varying(160) NOT NULL DEFAULT '';
                """);
        }

        private static void EnsureAgendaTable(CitasDbContext context)
        {
            context.Database.ExecuteSqlRaw("""
                CREATE TABLE IF NOT EXISTS "Agenda" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CitaId" integer NOT NULL,
                    "PacienteId" integer NOT NULL,
                    "MedicoId" integer NOT NULL,
                    "PacienteNombre" character varying(220) NOT NULL,
                    "MedicoNombre" character varying(220) NOT NULL,
                    "Fecha" date NOT NULL,
                    "Hora" time without time zone NOT NULL,
                    "Motivo" character varying(500) NOT NULL,
                    "Estado" character varying(50) NOT NULL,
                    CONSTRAINT "PK_Agenda" PRIMARY KEY ("Id")
                );
                """);

            context.Database.ExecuteSqlRaw("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Agenda_CitaId"
                ON "Agenda" ("CitaId");
                """);
        }

        private static Paciente EnsurePaciente(
            CitasDbContext context,
            string nombre,
            string apellido,
            string email,
            string telefono)
        {
            var paciente = context.Pacientes.FirstOrDefault(p => p.Email == email);
            if (paciente != null)
                return paciente;

            paciente = new Paciente
            {
                Nombre = nombre,
                Apellido = apellido,
                Email = email,
                Telefono = telefono
            };

            context.Pacientes.Add(paciente);
            return paciente;
        }

        private static Medico EnsureMedico(
            CitasDbContext context,
            string nombre,
            string apellido,
            string especialidad,
            string numeroLicencia)
        {
            var medico = context.Medicos.FirstOrDefault(m => m.NumeroLicencia == numeroLicencia);
            if (medico != null)
                return medico;

            medico = new Medico
            {
                Nombre = nombre,
                Apellido = apellido,
                Especialidad = especialidad,
                NumeroLicencia = numeroLicencia
            };

            context.Medicos.Add(medico);
            return medico;
        }

        private static void EnsureCita(
            CitasDbContext context,
            int pacienteId,
            int medicoId,
            DateOnly fecha,
            TimeOnly hora,
            string motivo)
        {
            if (context.Citas.Any(c => c.PacienteId == pacienteId && c.MedicoId == medicoId && c.Motivo == motivo))
                return;

            context.Citas.Add(new Cita
            {
                PacienteId = pacienteId,
                MedicoId = medicoId,
                Fecha = fecha,
                Hora = hora,
                Motivo = motivo,
                Estado = "Pendiente"
            });
        }

        private static void EnsureUsuario(
            CitasDbContext context,
            string nombreUsuario,
            string password,
            string nombreCompleto,
            string rol,
            int? pacienteId,
            int? medicoId)
        {
            var usuario = context.Usuarios.FirstOrDefault(u => u.NombreUsuario == nombreUsuario);
            if (usuario != null)
            {
                usuario.NombreCompleto = nombreCompleto;
                usuario.Rol = rol;
                usuario.PacienteId = pacienteId;
                usuario.MedicoId = medicoId;
                return;
            }

            context.Usuarios.Add(new Usuario
            {
                NombreUsuario = nombreUsuario,
                NombreCompleto = nombreCompleto,
                PasswordHash = PasswordHashService.Hash(password),
                Rol = rol,
                PacienteId = pacienteId,
                MedicoId = medicoId
            });
        }

        private static void SyncAgenda(CitasDbContext context)
        {
            var citas = context.Citas.ToList();
            var pacientes = context.Pacientes.ToDictionary(p => p.Id);
            var medicos = context.Medicos.ToDictionary(m => m.Id);

            foreach (var cita in citas)
            {
                var agenda = context.Agenda.FirstOrDefault(a => a.CitaId == cita.Id);
                if (agenda == null)
                {
                    agenda = new Agenda { CitaId = cita.Id };
                    context.Agenda.Add(agenda);
                }

                pacientes.TryGetValue(cita.PacienteId, out var paciente);
                medicos.TryGetValue(cita.MedicoId, out var medico);

                agenda.PacienteId = cita.PacienteId;
                agenda.MedicoId = cita.MedicoId;
                agenda.PacienteNombre = paciente == null
                    ? string.Empty
                    : $"{paciente.Nombre} {paciente.Apellido}";
                agenda.MedicoNombre = medico == null
                    ? string.Empty
                    : $"{medico.Nombre} {medico.Apellido}";
                agenda.Fecha = cita.Fecha;
                agenda.Hora = cita.Hora;
                agenda.Motivo = cita.Motivo;
                agenda.Estado = cita.Estado;
            }

            context.SaveChanges();
        }
    }
}
